package com.tyrdanov.auth_service.factory;

import java.util.UUID;

import com.tyrdanov.auth_service.dto.CreateTransactionDto;
import com.tyrdanov.auth_service.dto.TransferRequest;
import com.tyrdanov.auth_service.dto.UpdateTransactionDto;
import com.tyrdanov.auth_service.enums.Currency;
import com.tyrdanov.auth_service.enums.Status;

public class TransactionDtoFactory {
    public static UpdateTransactionDto buildUpdateDto(
            UUID id,
            TransferRequest request,
            Status status) {
        final var amount = request.getAmount();
        final var description = request.getDescription();
        final var senderId = request.getSenderId();
        final var receiverId = request.getReceiverId();
        final var categoryId = request.getCategoryId();

        return UpdateTransactionDto
                .builder()
                .id(id)
                .amount(amount)
                .description(description)
                .senderId(senderId)
                .receiverId(receiverId)
                .status(status)
                .currency(Currency.RUB)
                .categoryId(categoryId)
                .build();
    }

    public static CreateTransactionDto buildCreateDto(TransferRequest request) {
        final var amount = request.getAmount();
        final var description = request.getDescription();
        final var senderId = request.getSenderId();
        final var receiverId = request.getReceiverId();
        final var categoryId = request.getCategoryId();

        return CreateTransactionDto
                .builder()
                .amount(amount)
                .currency(Currency.RUB)
                .description(description)
                .senderId(senderId)
                .receiverId(receiverId)
                .categoryId(categoryId)
                .build();
    }

    private TransactionDtoFactory() {
        // Empty constructor so that it is not generated by default
    }
}
